### ISSUE TITLE
How to use inventory file

### ISSUE THREAD

**Issue by dorsany** [kriansa/ansible-bundler#6]
I want to use the ansible to run commands also on multiple servers.

There is a way to use an inventory file? 

Like ```ansible-playbook --inventory <host.ini file>```

**Comment by kriansa** [comment]
What exactly are you trying to do? Bundle a playbook into a single file then running it locally/CI?

**Comment by dorsany** [comment]
We are trying to use the ansible  abilities to configure also remote servers. For example:
my ```playbook.yml```:
```
- hosts: all
  gather_facts: true
  become: yes
  tasks:
    - name: Reboot node
      reboot:
        reboot_timeout: 600
        pre_reboot_delay: 60
        post_reboot_delay: 30
```
and my ```inventory.ini``` file:
```
[all]
master1 ansible_connection=local
node1 ansible_host=192.168.1.110
node2 ansible_host=192.168.1.120

[all:vars]
ansible_port=22
ansible_user=user
ansible_ssh_private_key_file=/root/.ssh/id_rsa
```
it seems that in the code there is restriction only to ```--inventory="localhost,"``` and ```--connection=local```

https://github.com/kriansa/ansible-bundler/blob/38ab71f7bb8557cb72f78b6c60516b3bd43bdaa7/app/lib/run-playbook.sh#L98-L102

any way to achieve that?
